### ISSUE TITLE
Output

### ISSUE THREAD

**Issue by hairuiC** [tue-mps/rescience-ijcai2017-230#1]
Hi,

Sorry for the bother. I'm running the code and I met some problems.

When I'm using faster_rcnn_resnet50 as a model and get output. The output is a dict. Not a list.

But in your code in training.py, row 156, you are using **output[1]** to get results from the output. The program returns a KeyError.

I want to know why is that? My pytorch version is 1.8.1. Maybe they are different?

Or could you please explain 

detections = output[1]

what this detections place for? What's the type and the size?

and what is output[0]?

Thank you very much. I'm waiting for your reply.

**Comment by JarlLemmens** [comment]
Hi,

sorry for the late reply, but this could be a pytorch version issue, as I am using 1.8.0

anyway, in my case output is a list of size 2 containing a dictionary of losses as output[0] and a list of detections as output[1]
the losses are 'loss_classifier', 'loss_box_reg', 'loss_objectness' and 'loss_rpn_box_reg'.
I believe your output is just a dict containing the losses, no detections, but these are not used anyway, just for counting the number of boxes which is then not used.
